"""
Generate a sample EPUB ebook for extraction demos.

Creates sample_book.epub - a 4-chapter ebook about data science.
Uses ebooklib to build a well-structured EPUB with:
  - Metadata (title, author, language)
  - Table of contents
  - 4 chapters with HTML content (paragraphs, lists, tables)

The EPUB format is essentially a ZIP archive of XHTML files with metadata.
"""

from pathlib import Path

from ebooklib import epub

SAMPLE_DIR = Path(__file__).parent


def create_chapter(
    filename: str,
    title: str,
    html_body: str,
    lang: str = "en",
) -> epub.EpubHtml:
    """Create an EPUB chapter with proper HTML wrapping."""
    chapter = epub.EpubHtml(title=title, file_name=filename, lang=lang)
    chapter.content = f"<html><body><h1>{title}</h1>{html_body}</body></html>"
    return chapter


def generate_sample_book() -> Path:
    """Generate a 4-chapter sample EPUB about data science."""
    book = epub.EpubBook()

    # --- Metadata ---
    book.set_identifier("datasci-intro-2025")
    book.set_title("Introduction to Data Science")
    book.set_language("en")
    book.add_author("AI Research Lab")
    book.add_metadata(
        "DC",
        "description",
        "A beginner-friendly introduction to data science concepts.",
    )
    book.add_metadata("DC", "publisher", "RAG Source Publishing")

    # --- Chapter 1: What is Data Science? ---
    ch1_body = """
    <p>Data science is an interdisciplinary field that uses scientific methods,
    processes, algorithms, and systems to extract knowledge and insights from
    structured and unstructured data. It combines expertise from statistics,
    computer science, and domain knowledge to analyze complex datasets.</p>

    <p>The field emerged from the growing volume of data generated by digital
    systems, social media, sensors, and scientific instruments. Organizations
    across every industry now rely on data science to make evidence-based
    decisions, optimize operations, and discover hidden patterns in their data.</p>

    <p>A data scientist typically works through several stages: data collection
    and cleaning, exploratory data analysis, feature engineering, model building,
    evaluation, and deployment. Each stage requires different skills and tools,
    making data science one of the most versatile careers in technology today.</p>
    """
    ch1 = create_chapter("ch01.xhtml", "What is Data Science?", ch1_body)

    # --- Chapter 2: Statistical Methods ---
    ch2_body = """
    <p>Statistics forms the mathematical foundation of data science. Descriptive
    statistics summarize data through measures like mean, median, mode, variance,
    and standard deviation. These provide a quick overview of the central tendency
    and spread of a dataset before deeper analysis begins.</p>

    <p>Inferential statistics allow data scientists to draw conclusions about
    populations based on sample data. Hypothesis testing, confidence intervals,
    and regression analysis are essential tools. Understanding p-values, statistical
    significance, and the difference between correlation and causation is critical
    for making valid conclusions from data.</p>

    <p>Bayesian statistics offers an alternative framework where prior knowledge
    is formally incorporated into the analysis. This approach is particularly
    valuable when working with small datasets or when domain expertise should
    influence the model. Bayesian methods are widely used in A/B testing,
    spam filtering, and medical diagnosis.</p>

    <p>Key statistical methods used in data science include:</p>
    <ul>
        <li>Linear and logistic regression for predictive modeling</li>
        <li>ANOVA for comparing group means</li>
        <li>Chi-square tests for categorical data analysis</li>
        <li>Time series analysis for temporal patterns</li>
        <li>Principal Component Analysis (PCA) for dimensionality reduction</li>
    </ul>
    """
    ch2 = create_chapter("ch02.xhtml", "Statistical Methods", ch2_body)

    # --- Chapter 3: Machine Learning Basics ---
    ch3_body = """
    <p>Machine learning is a subset of artificial intelligence that enables
    systems to learn and improve from experience without being explicitly
    programmed. It focuses on developing algorithms that can access data,
    learn from it, and make predictions or decisions. The three main types
    are supervised learning, unsupervised learning, and reinforcement learning.</p>

    <p>Supervised learning uses labeled training data to learn a mapping from
    inputs to outputs. Classification assigns discrete labels (spam vs. not spam),
    while regression predicts continuous values (house prices). Popular algorithms
    include decision trees, random forests, support vector machines, and neural
    networks. Model evaluation uses metrics like accuracy, precision, recall, and
    F1 score.</p>

    <p>Unsupervised learning finds hidden patterns in unlabeled data. Clustering
    algorithms like K-means and DBSCAN group similar data points together.
    Dimensionality reduction techniques like PCA and t-SNE help visualize
    high-dimensional data. These methods are valuable for customer segmentation,
    anomaly detection, and exploratory data analysis.</p>

    <p>Common algorithms and their typical use cases:</p>
    <table>
        <tr>
            <th>Algorithm</th>
            <th>Type</th>
            <th>Use Case</th>
        </tr>
        <tr>
            <td>Linear Regression</td>
            <td>Supervised</td>
            <td>Price prediction, trend analysis</td>
        </tr>
        <tr>
            <td>Random Forest</td>
            <td>Supervised</td>
            <td>Classification, feature importance</td>
        </tr>
        <tr>
            <td>K-Means</td>
            <td>Unsupervised</td>
            <td>Customer segmentation, grouping</td>
        </tr>
        <tr>
            <td>Neural Networks</td>
            <td>Supervised</td>
            <td>Image recognition, NLP, complex patterns</td>
        </tr>
    </table>
    """
    ch3 = create_chapter("ch03.xhtml", "Machine Learning Basics", ch3_body)

    # --- Chapter 4: Future Directions ---
    ch4_body = """
    <p>The future of data science is shaped by rapid advances in artificial
    intelligence, growing data volumes, and increasing computational power.
    Large language models and foundation models are transforming how we approach
    natural language processing, computer vision, and multimodal tasks.
    AutoML tools are democratizing machine learning by automating model selection
    and hyperparameter tuning.</p>

    <p>Ethical considerations are becoming central to data science practice.
    Fairness, accountability, transparency, and privacy are no longer optional.
    Regulations like GDPR and emerging AI governance frameworks require data
    scientists to consider the societal impact of their models. Explainable AI
    (XAI) techniques help stakeholders understand model decisions and build trust.</p>

    <p><strong>Conclusion:</strong> Data science continues to evolve at a remarkable
    pace. Success in this field requires not only technical skills in programming,
    statistics, and machine learning, but also critical thinking, communication,
    and an understanding of the ethical implications of working with data. The
    opportunities for those entering the field today are vast and growing.</p>
    """
    ch4 = create_chapter("ch04.xhtml", "Future Directions", ch4_body)

    # --- Add chapters to book ---
    book.add_item(ch1)
    book.add_item(ch2)
    book.add_item(ch3)
    book.add_item(ch4)

    # --- Table of contents ---
    book.toc = [
        epub.Link("ch01.xhtml", "What is Data Science?", "ch01"),
        epub.Link("ch02.xhtml", "Statistical Methods", "ch02"),
        epub.Link("ch03.xhtml", "Machine Learning Basics", "ch03"),
        epub.Link("ch04.xhtml", "Future Directions", "ch04"),
    ]

    # --- Navigation files (required by EPUB spec) ---
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # --- Spine (reading order) ---
    book.spine = ["nav", ch1, ch2, ch3, ch4]

    # --- Write EPUB file ---
    output_path = SAMPLE_DIR / "sample_book.epub"
    epub.write_epub(str(output_path), book, {})

    print(f"  Created: {output_path.name}")
    print("    Title:    Introduction to Data Science")
    print("    Author:   AI Research Lab")
    print("    Chapters: 4")

    return output_path


if __name__ == "__main__":
    print("Generating sample EPUB for extraction demos...")
    print()
    generate_sample_book()
    print()
    print("Done! Sample EPUB is in:", SAMPLE_DIR)
